name: flutter_education_mad_brains
description: "A education project from Mad Brains."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/posters/img1.jpg
    - assets/posters/img2.jpg
    - assets/posters/img3.jpg
    - assets/posters/img4.jpg
    - assets/posters/img5.jpg

  fonts:
    - family: Anta
      fonts:
        - asset: fonts/Anta-Regular.ttf
